### PR TITLE
Updated core formatter RegEx to handle foreign language articles

### PR DESCRIPTION
**Pull request by erikreedstrom**
- "de", "ta", "gada", and "yil" are now supported
- See: http://rubular.com/r/sxjV9gYLpA

es-ES Before:

new Date().toString("dd' de 'MMMM' de 'yyyy")
"12' 12e 'enero' 12e '2012"

es-ES After:

new Date().toString("dd' de 'MMMM' de 'yyyy")
"12' de 'enero' de '2012"

### CODE REVIEW

**Comment by eric** [comment]
Would you mind adding a test or two for this?

**Comment by eric** [comment]
I'm seeing some test failures with this that aren't in `next`:

```

node_test.coffee
✖ partial: Biasing - biasing to the past, parse the day of the month tomorrow to last month

AssertionError: false == true
      function () {
        // The date is less than now
        return this.date < new Date() &&
          // and the hour is 3pm
          this.date.getHours() == 15 &&
          // make sure the day of the month is right
          this.date.getDate() == this.nextDay.getDate();
      }
    at Object.ok (/Users/eric/src/Datejs/test/node/node_modules/nodeunit/lib/types.js:81:39)
    at /Users/eric/src/Datejs/test/node/node_test.coffee:50:18

✖ partial: Biasing - biasing to the past, parse the day and the month of next month to a year ago

AssertionError: false == true
      function () {
        // The date is less than now
        return this.date < new Date() &&
          // and the hour is 3pm
          this.date.getHours() == 15 &&
          // make sure the day of the month is right
          this.date.getDate() == this.nextMonth.getDate();
      }
    at Object.ok (/Users/eric/src/Datejs/test/node/node_modules/nodeunit/lib/types.js:81:39)
    at /Users/eric/src/Datejs/test/node/node_test.coffee:50:18

✖ partial: Biasing - biasing to the future, parse the day of the month for yesterday to next month

AssertionError: false == true
      function () {
        // The date is greater than now
        return this.date > new Date() &&
          // and the hour is 3pm
          this.date.getHours() == 15 &&
          // make sure the day of the month is right
          this.date.getDate() == this.previousDay.getDate();
      }
    at Object.ok (/Users/eric/src/Datejs/test/node/node_modules/nodeunit/lib/types.js:81:39)
    at /Users/eric/src/Datejs/test/node/node_test.coffee:50:18
```

**Comment by erikreedstrom** [comment]
Yeah, no problem.  It may be a couple days before I can get the tests done.

I'm a little surprised that you have parse failures as this was a formatting change only.  Can you expand on the issues you're seeing?

I've also added an additional format to the parser: "yyyy-MM-dd".

**Comment by eric** [comment]
I haven't had a chance to dig into why those tests fail with the change — I'm sure it's something subtle...

**Comment by erikreedstrom** [comment]
It fails in biasing for next as well. I should have checked the tests!
 It's the "dS". I'll have to update the regex to allow for the ordinal
following a single d.

Sent from my diamond encrusted, hand held talking device that fell
from the Heavens

On Jan 12, 2012, at 4:06 PM, Eric Lindvall
reply@reply.github.com
wrote:

**Pull request closed without merging**
